### ISSUE TITLE
Doesn't support jsconfig.json path alias.

### ISSUE THREAD

**Issue by itaditya** [jescalan/babel-plugin-import-glob-array#14]
Hello @jescalan. First of all thanks for making such a superb tool. I was looking for something like this to collect data from MDX blog posts in my Next.js blog and this solves the problem in a really neat way.

I ran into an issue however when I tried using babel module alias in the module import path. Next.js supports it via jsconfig.json.

Am I doing something wrong here? You can see my exact steps in this PR-

https://github.com/itaditya/website/pull/48/files

**Comment by jescalan** [comment]
You're correct it does not support `jsconfig.json` aliases. You will need to use the full path for imports using this plugin.
